In [6]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [7]:
!mkdir drive
!google-drive-ocamlfuse drive

mkdir: cannot create directory ‘drive’: File exists


In [8]:
import os 
os.chdir("/content/drive/Colab_Notebooks/23december")
!pwd

/content/drive/Colab_Notebooks/23december


In [9]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical

import numpy as np
import pandas as pd

import csv

In [24]:
def one_hot_encoding (y_train):
  y_train = y_train
  row = y_train.shape[0]
  i = 0
  ohe = []

  row = y_train.shape[0]
  i = 0
  ohe = []


#y_train: 60k so this array should be 60k tuples.
  for i in range(row):
#number 5: ohe array should be like this : [5, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
#number 6: ohe array should be like this : [6, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
    temp = [y_train[i]]
    for j in range(10):
      if (j == y_train[i]):
        temp.append(1)
      else:
        temp.append(0)
    ohe = ohe + [temp]  

  return ohe 
    

In [26]:
def main():
  (x_train,y_train), (x_test,y_test) = mnist.load_data()
  print("x_train",x_train.shape)
  print("y_train",y_train.shape)
  print("x_test",x_test.shape)
  print("y_test",y_test.shape)

  print("y_train:[",y_train[0],y_train[1],y_train[2],y_train[3],y_train[4],y_train[5],y_train[6],"...]")

  y_train_ohe = to_categorical(y_train)
  print("y_train_ohe:",y_train_ohe)
  print("y_train_ohe dim:",y_train_ohe.shape)
  print("y_train[0]:",y_train[0]," its ohe:",y_train_ohe[0])

  column=['y_value','num_0','num_1','num_2','num_3','num_4','num_5','num_6','num_7','num_8','num_9']

  filename = 'y_train_ohe.csv'
  with open(filename, 'w', newline='') as outcsv:
    writer = csv.writer(outcsv)
    writer.writerow(column)
  
  #transform y_train array to one_hot_encoding array
  #with this, we will use it in CNN for categorization.
  ohe = one_hot_encoding(y_train) 

  #append new rows into existing csv file 
  append_new_row(filename,ohe)
      

In [27]:
from csv import writer
def append_new_row (filename, ndarr):
  file_name = filename
  ndarr = ndarr
  row = len(ndarr)

  with open(file_name, 'a+', newline='') as write_obj:
    # Create a writer object from csv module
    csv_writer = writer(write_obj)
    # Add contents of list as last row in the csv file
    for i in range(row):
      csv_writer.writerow(ndarr[i])
    

In [30]:
if __name__ == '__main__':
  print('code executed')
  main()

#run different main source
else:
  print("code executed by other main running progress")

code executed
x_train (60000, 28, 28)
y_train (60000,)
x_test (10000, 28, 28)
y_test (10000,)
y_train:[ 5 0 4 1 9 2 1 ...]
y_train_ohe: [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
y_train_ohe dim: (60000, 10)
y_train[0]: 5  its ohe: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [31]:
y_ohe = pd.read_csv('./y_train_ohe.csv')
y_ohe.head(25)

y_value  num_0  num_1  num_2  num_3  ...  num_5  num_6  num_7  num_8  num_9
0         5      0      0      0      0  ...      1      0      0      0      0
1         0      1      0      0      0  ...      0      0      0      0      0
2         4      0      0      0      0  ...      0      0      0      0      0
3         1      0      1      0      0  ...      0      0      0      0      0
4         9      0      0      0      0  ...      0      0      0      0      1
5         2      0      0      1      0  ...      0      0      0      0      0
6         1      0      1      0      0  ...      0      0      0      0      0
7         3      0      0      0      1  ...      0      0      0      0      0
8         1      0      1      0      0  ...      0      0      0      0      0
9         4      0      0      0      0  ...      0      0      0      0      0
10        3      0      0      0      1  ...      0      0      0      0      0
11        5      0      0      0      0  ...      1      0      0      0      0
12        3      0      0      0      1  ...      0      0      0      0      0
13        6      0      0      0      0  ...      0      1      0      0      0
14        1      0      1      0      0  ...      0      0      0      0      0
15        7      0      0      0      0  ...      0      0      1      0      0
16        2      0      0      1      0  ...      0      0      0      0      0
17        8      0      0      0      0  ...      0      0      0      1      0
18        6      0      0      0      0  ...      0      1      0      0      0
19        9      0      0      0      0  ...      0      0      0      0      1
20        4      0      0      0      0  ...      0      0      0      0      0
21        0      1      0      0      0  ...      0      0      0      0      0
22        9      0      0      0      0  ...      0      0      0      0      1
23        1      0      1      0      0  ...      0      0      0      0      0
24        1      0      1      0      0  ...      0      0      0      0      0

[25 rows x 11 columns]